### ISSUE TITLE
Add marker to position in OSM Map

### ISSUE THREAD

**Issue by fx99-D** [mfdz/nvbw-osm-stop-comparison#15]
Generate eg.
https://www.openstreetmap.org/?mlat=48.57171&mlon=8.81367#map=17/48.57171/8.81367&layers=ON
instead of 
https://www.openstreetmap.org/#map=17/48.57171/8.81367&layers=ON 
in link to "Koordinaten"

This allows a better localisation of expected position.

**Comment by hbruch** [comment]
Changed. Thanks for the suggestion.
