### ISSUE TITLE
Typo in MATCHED_AMBIGOUSLY state

### ISSUE THREAD

**Issue by 1Maxnet1** [mfdz/nvbw-osm-stop-comparison#16]
The state should be called `MATCHED_AMBIGUOUSLY`. I can offer to fix the typo in a little PR, however this might lead to issues, when comparing evaluations with this tool from before and after the change. Any ideas how to avoid that or proposals what to do about that?

**Comment by hbruch** [comment]
Thanks for reporting, and indeed, this requires corrections in other places. No need to provide a PR, I'll fix this.
